TAL-7: Create Puppy Tests
iiddd/test-automation-learning pull request #10
Opened 2024-09-30 21:18 UTC by Manuyafox

Created 3 test for wrong credentials and 1 broken test for check all is displayed (this was not part of my plans)

2024-11-06 10:44 UTC, ElKordel commented on src/main/java/org/example/utils/WaitUtils.java
> +
Is this necessary?

2024-11-06 10:56 UTC, ElKordel reviewed
think it's ok

2024-11-12 16:42 UTC, Manuyafox commented on src/main/java/org/example/utils/WaitUtils.java
> +
Андрей просил добавить приватный конструктор

2024-11-12 20:35 UTC, iiddd requested changes

2024-11-14 15:34 UTC, Manuyafox commented on src/main/java/org/example/utils/WaitUtils.java
> +
This is a private constructor that Andrey asked to be added

2024-11-15 07:04 UTC, iiddd approved these changes

2024-11-15 16:41 UTC, merged