TAL-14: Registration Happy Flow Test
iiddd/test-automation-learning pull request #14
Opened 2024-11-06 10:37 UTC by ElKordel

2024-11-12 20:40 UTC, iiddd requested changes

2024-11-12 20:40 UTC, iiddd commented on src/main/java/org/example/pages/LoginPage.java
> +    public LoginPage loginTestAccount() {
maybe good to rename to 'loginWithTestAccount'?

2024-11-12 20:40 UTC, iiddd commented on src/main/java/org/example/pages/LoginPage.java
> +        getDriver().findElement(By.xpath("//a[@data-target='#collapseUsers']")).click();
I'd suggest to extract By to a page constant

2024-11-14 15:30 UTC, Manuyafox approved these changes

2024-11-15 06:58 UTC, iiddd approved these changes

2024-11-15 15:31 UTC, merged