Tal-16: Login Page Testcases
iiddd/test-automation-learning pull request #15
Opened 2024-11-14 17:56 UTC by MrGelerter

2024-11-17 11:18 UTC, YanaMr commented on src/test/resources/EmptyCredentialsTestCases
> +- Stay on the «Welcome to Puppy Bank» page
а ошибки там никакой нет? 
я бы сначала ожидала сообщение с ошибкой, а уже потом что ничего не произошло

2024-11-17 11:18 UTC, YanaMr commented on src/test/resources/EmptyCredentialsTestCases
> +- Stay on the «Welcome to Puppy Bank» page
а ошибки там никакой нет? 
я бы сначала ожилаоа сообщение с ошибкой,а  уже потом что ничего не произошло

2024-11-17 11:18 UTC, YanaMr commented on src/test/resources/EmptyCredentialsTestCases
> +- Stay on the «Welcome to Puppy Bank» page
а ошибки там никакой нет? 
я бы сначала ожилаоа сообщение с ошибкой,а  уже потом что ничего не произошло

2024-11-17 11:18 UTC, YanaMr commented on src/test/resources/EmptyCredentialsTestCases
> +2) Empty Login Test
Empty Username Field Test --- иначе не понятно о чем речь

2024-11-17 11:18 UTC, YanaMr commented on src/test/resources/EmptyCredentialsTestCases
> +3) Empty Password Test
Empty Password Field Test

2025-02-24 17:20 UTC, iiddd requested changes

2025-02-24 17:20 UTC, iiddd commented on src/test/resources/EmptyCredentialsTestCases
> +- Stay on the «Welcome to Puppy Bank» page
Я бы тут писал в формате от третьего лица о системе. Типа "User stays on the "Welcome to Puppy Bank" page

2025-02-24 17:20 UTC, iiddd commented on src/test/resources/EmptyCredentialsTestCases
> +2) Empty Login Test
Согласен

2025-02-28 13:52 UTC, closed without merging