TAL-25: Create Withdraw page tests
iiddd/test-automation-learning pull request #21
Opened 2024-12-18 19:35 UTC by Manuyafox

2024-12-24 13:03 UTC, iiddd requested changes

2024-12-24 13:03 UTC, iiddd commented on src/test/java/puppy/withdraw/ChangingAccountBalanceTest.java
> +    //private float ACCOUNT_BALANCE = ;
Shall we remove it?

2024-12-24 13:03 UTC, iiddd commented on src/test/java/puppy/withdraw/ChangingAccountBalanceTest.java
> +        //puppyAccountListPage
Same

2024-12-24 13:03 UTC, iiddd commented on src/test/java/puppy/withdraw/ChangingAccountBalanceTest.java
> +        //.getAccountBalance();
Same

2024-12-24 13:03 UTC, iiddd commented on src/test/java/puppy/withdraw/TooMuchAmountTest.java
> +    //private static final float HIGHER_BALANCE = ACCOUNT_BALANCE + 1;
Same

2024-12-24 13:03 UTC, iiddd commented on src/test/java/puppy/withdraw/TooMuchAmountTest.java
> +    //private float ACCOUNT_BALANCE = ;
Same

2024-12-24 13:03 UTC, iiddd commented on src/test/java/puppy/withdraw/TooMuchAmountTest.java
> +        //puppyAccountListPage
Same. Commented code.

2025-01-21 21:42 UTC, ElKordel approved these changes

2025-01-21 21:46 UTC, merged